### ISSUE TITLE
Finish EDNS option design

### ISSUE THREAD

**Issue by vttale** [vttale/serve-stale#5]
Current EDNS option intro says:

>    [ This section will be fleshed out a bit more thoroughly if there is
>    interest in pursuing the option. ]

Initial feedback is in favour of pursuing it, so work it up more rigourously.

**Comment by wkumari** [comment]
Strong consensus at IETF103 was to remove it - https://datatracker.ietf.org/doc/minutes-103-dnsop/
Done in commit  8daf996
